### ISSUE TITLE
A Reflected XSS vulnerability in webhook.php

### ISSUE THREAD

**Issue by jgj212** [trollepierre/tdm#50]
Hello:
I have find a Reflected XSS vulnerability.

The vulnerability exists due to insufficient filtration of user-supplied data in "challenge" HTTP parameter that will be passed to "tdm-master/webhook.php". The infected source code is line 5, there is no protection on $_GET['challenge'], if it contains evil js code, line 72 will trigger untrusted code to be executed on the browser side.
![c1](https://cloud.githubusercontent.com/assets/1484292/24281387/3be64f5c-1093-11e7-9624-169cb978adac.png)
![c2](https://cloud.githubusercontent.com/assets/1484292/24281388/3c1096b8-1093-11e7-9bf2-011b9b6447e1.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/tdm-master/webhook.php?challenge="><script>alert(1);</script><"

The follow scrrenshot is the result to click the upper url ( win7 sp1 x64 + firefox 51.0.1 32bit ):
![s1](https://cloud.githubusercontent.com/assets/1484292/24281454/bc7bd27c-1093-11e7-91cb-3c72f6f3396f.png)

Discoverer: Haojun Hou, DongWang in ADLab of Venustech

**Comment by jzySaber1996** [comment]
Hello, we're investigating the issue reports in security. Since we observed that this issue may relate to security, has it been disclosed in CVE already? Thanks for your reply.
